In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
import numpy as np
import pandas as pd

In [21]:
import pandas as pd

# Load the actual CSV file
file_path = '/content/drive/MyDrive/Deep Learning/Lecture 30 - 40/diabetes.csv'
df = pd.read_csv(file_path)

# Display the data in tabular format
display(df.head())

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [22]:
# Now showing the actual diabetes data table
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [23]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [24]:
X = df.drop(columns=['Outcome'])
y = df['Outcome']

In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Scaling the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print(f"Training set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")

Training set size: (614, 8)
Test set size: (154, 8)

In [26]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [28]:
model.fit(X_train,y_train,epochs=100,batch_size=32,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6661 - loss: 0.6493 - val_accuracy: 0.6169 - val_loss: 0.6518
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7020 - loss: 0.6102 - val_accuracy: 0.6688 - val_loss: 0.6155
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7166 - loss: 0.5788 - val_accuracy: 0.6883 - val_loss: 0.5891
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7280 - loss: 0.5550 - val_accuracy: 0.7143 - val_loss: 0.5680
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5353 - val_accuracy: 0.7208 - val_loss: 0.5516
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.5190 - val_accuracy: 0.7273 - val_loss: 0.5394
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.5055 - val_accuracy: 0.7273 - val_loss: 0.5288
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4952 - val_accuracy: 0.7403 - val_loss: 0.5238
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4854 - val_accuracy: 0.7532 - val_loss: 0.5155
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4774 - val_accuracy: 0.7662 - val_loss: 0.5103
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4702 - val_accuracy: 0.7597 - val_loss: 0.5076
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4647 - val_accuracy: 0.7662 - val_loss: 0.5041
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4599 - val_accuracy: 0.7597 - val_loss: 0.5018
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4571 - val_accuracy: 0.7727 - val_loss: 0.5007
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4540 - val_accuracy: 0.7597 - val_loss: 0.5026
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4519 - val_accuracy: 0.7662 - val_loss: 0.5025
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4488 - val_accuracy: 0.7597 - val_loss: 0.5025
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4464 - val_accuracy: 0.7597 - val_loss: 0.5016
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4445 - val_accuracy: 0.7597 - val_loss: 0.5016
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4427 - val_accuracy: 0.7597 - val_loss: 0.5027
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4418 - val_accuracy: 0.7532 - val_loss: 0.5050
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4403 - val_accuracy: 0.7468 - val_loss: 0.5059
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4387 - val_accuracy: 0.7532 - val_loss: 0.5051
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4377 - val_accuracy: 0.7532 - val_loss: 0.5057
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4365 - val_accuracy: 0.7532 - val_loss: 0.5111
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4350 - val_accuracy: 0.7532 - val_loss: 0.5117
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4341 - val_accuracy: 0.7532 - val_loss: 0.5116
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7964 - loss: 0.4324 - val_accuracy: 0.7532 - val_loss: 0.5147
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4319 - val_accuracy: 0.7468 - val_loss: 0.5124
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4306 - val_accuracy: 0.7468 - val_loss: 0.5145
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4306 - val_accuracy: 0.7532 - val_loss: 0.5147
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4290 - val_accuracy: 0.7468 - val_loss: 0.5161
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4279 - val_accuracy: 0.7532 - val_loss: 0.5177
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4269 - val_accuracy: 0.7532 - val_loss: 0.5168
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4265 - val_accuracy: 0.7532 - val_loss: 0.5169
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4255 - val_accuracy: 0.7532 - val_loss: 0.5156
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4248 - val_accuracy: 0.7468 - val_loss: 0.5145
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4238 - val_accuracy: 0.7532 - val_loss: 0.5148
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4233 - val_accuracy: 0.7468 - val_loss: 0.5142
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4228 - val_accuracy: 0.7468 - val_loss: 0.5161
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4221 - val_accuracy: 0.7532 - val_loss: 0.5170
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4214 - val_accuracy: 0.7597 - val_loss: 0.5167
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4204 - val_accuracy: 0.7532 - val_loss: 0.5165
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4197 - val_accuracy: 0.7532 - val_loss: 0.5177
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4193 - val_accuracy: 0.7532 - val_loss: 0.5187
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4185 - val_accuracy: 0.7532 - val_loss: 0.5190
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4182 - val_accuracy: 0.7597 - val_loss: 0.5188
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4174 - val_accuracy: 0.7597 - val_loss: 0.5205
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4172 - val_accuracy: 0.7532 - val_loss: 0.5201
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4168 - val_accuracy: 0.7532 - val_loss: 0.5205
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4164 - val_accuracy: 0.7597 - val_loss: 0.5212
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4162 - val_accuracy: 0.7532 - val_loss: 0.5229
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4151 - val_accuracy: 0.7532 - val_loss: 0.5239
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4149 - val_accuracy: 0.7532 - val_loss: 0.5236
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4139 - val_accuracy: 0.7532 - val_loss: 0.5227
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4132 - val_accuracy: 0.7532 - val_loss: 0.5229
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4133 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4122 - val_accuracy: 0.7597 - val_loss: 0.5226
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4122 - val_accuracy: 0.7597 - val_loss: 0.5233
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4107 - val_accuracy: 0.7597 - val_loss: 0.5237
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4114 - val_accuracy: 0.7597 - val_loss: 0.5252
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4107 - val_accuracy: 0.7532 - val_loss: 0.5249
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4099 - val_accuracy: 0.7597 - val_loss: 0.5239
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4101 - val_accuracy: 0.7532 - val_loss: 0.5231
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4089 - val_accuracy: 0.7532 - val_loss: 0.5236
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4087 - val_accuracy: 0.7532 - val_loss: 0.5236
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4078 - val_accuracy: 0.7532 - val_loss: 0.5235
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4079 - val_accuracy: 0.7532 - val_loss: 0.5249
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4080 - val_accuracy: 0.7532 - val_loss: 0.5247
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4070 - val_accuracy: 0.7532 - val_loss: 0.5246
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.4066 - val_accuracy: 0.7532 - val_loss: 0.5249
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4060 - val_accuracy: 0.7597 - val_loss: 0.5247
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4066 - val_accuracy: 0.7597 - val_loss: 0.5270
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4058 - val_accuracy: 0.7597 - val_loss: 0.5256
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4051 - val_accuracy: 0.7597 - val_loss: 0.5293
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4050 - val_accuracy: 0.7597 - val_loss: 0.5275
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4045 - val_accuracy: 0.7662 - val_loss: 0.5245
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4040 - val_accuracy: 0.7532 - val_loss: 0.5248
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4031 - val_accuracy: 0.7532 - val_loss: 0.5255
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4030 - val_accuracy: 0.7597 - val_loss: 0.5243
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4034 - val_accuracy: 0.7532 - val_loss: 0.5244
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4019 - val_accuracy: 0.7468 - val_loss: 0.5246
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4022 - val_accuracy: 0.7597 - val_loss: 0.5234
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4026 - val_accuracy: 0.7468 - val_loss: 0.5229
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4011 - val_accuracy: 0.7468 - val_loss: 0.5226
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4012 - val_accuracy: 0.7468 - val_loss: 0.5235
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4006 - val_accuracy: 0.7597 - val_loss: 0.5216
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4008 - val_accuracy: 0.7532 - val_loss: 0.5240
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3997 - val_accuracy: 0.7468 - val_loss: 0.5265
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3993 - val_accuracy: 0.7468 - val_loss: 0.5274
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3993 - val_accuracy: 0.7468 - val_loss: 0.5258
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3993 - val_accuracy: 0.7468 - val_loss: 0.5291
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3991 - val_accuracy: 0.7468 - val_loss: 0.5258
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3980 - val_accuracy: 0.7468 - val_loss: 0.5273
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3984 - val_accuracy: 0.7468 - val_loss: 0.5258
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3984 - val_accuracy: 0.7468 - val_loss: 0.5238
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3974 - val_accuracy: 0.7532 - val_loss: 0.5266
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3968 - val_accuracy: 0.7532 - val_loss: 0.5281
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.3968 - val_accuracy: 0.7532 - val_loss: 0.5279
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3964 - val_accuracy: 0.7468 - val_loss: 0.5276

# for optimization we need to think manually that now what we have to do so to solve this we use keras tuner

In [29]:
X_train.shape[1]

8

In [55]:
!pip install -q -U keras-tuner
import keras_tuner as kt

In [56]:
import tensorflow as tf

def build_model(hp):
  model = Sequential()
  model.add(Input(shape=(X_train.shape[1],)))
  model.add(Dense(32, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  # Selection of optimizer
  hp_optimizer = hp.Choice('optimizer', ['adam', 'sgd', 'rmsprop', 'adadelta'])

  model.compile(optimizer=hp_optimizer, loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [57]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_loss',
    max_trials=5)

In [54]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 07s]
val_accuracy: 0.7532467544078827

Best val_accuracy So Far: 0.7694804966449738
Total elapsed time: 00h 00m 19s

In [ ]:
tuner.get_best_hyperparameters()[0].values

In [34]:
model=tuner.get_best_models(num_models=1)[0]

NameError: name 'tuner' is not defined

In [35]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 965 (3.77 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 644 (2.52 KB)

In [36]:
model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.8192 - loss: 0.3962 - val_accuracy: 0.7468 - val_loss: 0.5262
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.8241 - loss: 0.3962 - val_accuracy: 0.7532 - val_loss: 0.5268
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8192 - loss: 0.3952 - val_accuracy: 0.7468 - val_loss: 0.5278
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.8176 - loss: 0.3953 - val_accuracy: 0.7468 - val_loss: 0.5274
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8225 - loss: 0.3947 - val_accuracy: 0.7468 - val_loss: 0.5302
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8176 - loss: 0.3950 - val_accuracy: 0.7532 - val_loss: 0.5318
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8208 - loss: 0.3946 - val_accuracy: 0.7468 - val_loss: 0.5311
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8192 - loss: 0.3944 - val_accuracy: 0.7532 - val_loss: 0.5327
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8143 - loss: 0.3936 - val_accuracy: 0.7468 - val_loss: 0.5328
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8160 - loss: 0.3934 - val_accuracy: 0.7468 - val_loss: 0.5323
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.8176 - loss: 0.3928 - val_accuracy: 0.7468 - val_loss: 0.5319
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.8192 - loss: 0.3928 - val_accuracy: 0.7468 - val_loss: 0.5326
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.8143 - loss: 0.3932 - val_accuracy: 0.7468 - val_loss: 0.5340
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8176 - loss: 0.3924 - val_accuracy: 0.7468 - val_loss: 0.5321
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8143 - loss: 0.3921 - val_accuracy: 0.7468 - val_loss: 0.5336
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3917 - val_accuracy: 0.7468 - val_loss: 0.5326
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3916 - val_accuracy: 0.7468 - val_loss: 0.5323
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3913 - val_accuracy: 0.7468 - val_loss: 0.5326
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3916 - val_accuracy: 0.7468 - val_loss: 0.5334
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3905 - val_accuracy: 0.7468 - val_loss: 0.5344
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3917 - val_accuracy: 0.7468 - val_loss: 0.5341
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3894 - val_accuracy: 0.7532 - val_loss: 0.5327
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3906 - val_accuracy: 0.7532 - val_loss: 0.5341
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3899 - val_accuracy: 0.7468 - val_loss: 0.5346
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3892 - val_accuracy: 0.7532 - val_loss: 0.5364
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3893 - val_accuracy: 0.7532 - val_loss: 0.5374
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3890 - val_accuracy: 0.7468 - val_loss: 0.5358
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8208 - loss: 0.3881 - val_accuracy: 0.7532 - val_loss: 0.5349
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8208 - loss: 0.3884 - val_accuracy: 0.7468 - val_loss: 0.5363
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8208 - loss: 0.3884 - val_accuracy: 0.7468 - val_loss: 0.5332
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8208 - loss: 0.3874 - val_accuracy: 0.7468 - val_loss: 0.5328
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8192 - loss: 0.3870 - val_accuracy: 0.7532 - val_loss: 0.5319
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8225 - loss: 0.3869 - val_accuracy: 0.7468 - val_loss: 0.5327
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8225 - loss: 0.3876 - val_accuracy: 0.7532 - val_loss: 0.5325
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.8225 - loss: 0.3866 - val_accuracy: 0.7468 - val_loss: 0.5343
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8225 - loss: 0.3860 - val_accuracy: 0.7468 - val_loss: 0.5360
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8160 - loss: 0.3869 - val_accuracy: 0.7468 - val_loss: 0.5357
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.8160 - loss: 0.3860 - val_accuracy: 0.7468 - val_loss: 0.5355
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8160 - loss: 0.3859 - val_accuracy: 0.7468 - val_loss: 0.5336
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.8225 - loss: 0.3855 - val_accuracy: 0.7532 - val_loss: 0.5329
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8241 - loss: 0.3849 - val_accuracy: 0.7532 - val_loss: 0.5337
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8225 - loss: 0.3851 - val_accuracy: 0.7532 - val_loss: 0.5356
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8208 - loss: 0.3842 - val_accuracy: 0.7532 - val_loss: 0.5362
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3848 - val_accuracy: 0.7532 - val_loss: 0.5354
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3844 - val_accuracy: 0.7468 - val_loss: 0.5365
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3845 - val_accuracy: 0.7532 - val_loss: 0.5320
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3839 - val_accuracy: 0.7468 - val_loss: 0.5346
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3834 - val_accuracy: 0.7468 - val_loss: 0.5358
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3833 - val_accuracy: 0.7468 - val_loss: 0.5357
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3833 - val_accuracy: 0.7468 - val_loss: 0.5403
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3827 - val_accuracy: 0.7532 - val_loss: 0.5388
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3829 - val_accuracy: 0.7403 - val_loss: 0.5368
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3823 - val_accuracy: 0.7532 - val_loss: 0.5388
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3825 - val_accuracy: 0.7468 - val_loss: 0.5391
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3825 - val_accuracy: 0.7468 - val_loss: 0.5390
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3819 - val_accuracy: 0.7532 - val_loss: 0.5386
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3812 - val_accuracy: 0.7532 - val_loss: 0.5371
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3814 - val_accuracy: 0.7468 - val_loss: 0.5378
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3818 - val_accuracy: 0.7532 - val_loss: 0.5386
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3807 - val_accuracy: 0.7597 - val_loss: 0.5382
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3808 - val_accuracy: 0.7403 - val_loss: 0.5395
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3802 - val_accuracy: 0.7532 - val_loss: 0.5381
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3798 - val_accuracy: 0.7532 - val_loss: 0.5390
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3795 - val_accuracy: 0.7532 - val_loss: 0.5395
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3819 - val_accuracy: 0.7532 - val_loss: 0.5459
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8257 - loss: 0.3796 - val_accuracy: 0.7468 - val_loss: 0.5424
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3792 - val_accuracy: 0.7468 - val_loss: 0.5428
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8225 - loss: 0.3790 - val_accuracy: 0.7597 - val_loss: 0.5439
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8257 - loss: 0.3789 - val_accuracy: 0.7532 - val_loss: 0.5427
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8257 - loss: 0.3784 - val_accuracy: 0.7597 - val_loss: 0.5422
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8257 - loss: 0.3780 - val_accuracy: 0.7468 - val_loss: 0.5416
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8290 - loss: 0.3785 - val_accuracy: 0.7468 - val_loss: 0.5439
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3787 - val_accuracy: 0.7468 - val_loss: 0.5454
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3781 - val_accuracy: 0.7532 - val_loss: 0.5499
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3775 - val_accuracy: 0.7468 - val_loss: 0.5479
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3776 - val_accuracy: 0.7597 - val_loss: 0.5466
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3780 - val_accuracy: 0.7468 - val_loss: 0.5454
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3767 - val_accuracy: 0.7468 - val_loss: 0.5459
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3766 - val_accuracy: 0.7662 - val_loss: 0.5465
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3766 - val_accuracy: 0.7532 - val_loss: 0.5471
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3761 - val_accuracy: 0.7532 - val_loss: 0.5459
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3760 - val_accuracy: 0.7597 - val_loss: 0.5460
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3786 - val_accuracy: 0.7468 - val_loss: 0.5482
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3757 - val_accuracy: 0.7532 - val_loss: 0.5450
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3754 - val_accuracy: 0.7532 - val_loss: 0.5468
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3755 - val_accuracy: 0.7597 - val_loss: 0.5460
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3752 - val_accuracy: 0.7468 - val_loss: 0.5526
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3756 - val_accuracy: 0.7468 - val_loss: 0.5483
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3747 - val_accuracy: 0.7468 - val_loss: 0.5482
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3747 - val_accuracy: 0.7468 - val_loss: 0.5477
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3741 - val_accuracy: 0.7532 - val_loss: 0.5498
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3746 - val_accuracy: 0.7727 - val_loss: 0.5461
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3741 - val_accuracy: 0.7727 - val_loss: 0.5466
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3738 - val_accuracy: 0.7597 - val_loss: 0.5464
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3735 - val_accuracy: 0.7468 - val_loss: 0.5488
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3729 - val_accuracy: 0.7532 - val_loss: 0.5464
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3730 - val_accuracy: 0.7532 - val_loss: 0.5459
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3739 - val_accuracy: 0.7468 - val_loss: 0.5475
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3722 - val_accuracy: 0.7532 - val_loss: 0.5480
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3729 - val_accuracy: 0.7532 - val_loss: 0.5493

# How to find the right number of neurons in the hidden layers -->

In [42]:
def build_model(hp):
  model = Sequential()
  model.add(Input(shape=(X_train.shape[1],)))


  unit = hp.Int('units', min_value=8, max_value=128, step=8)

  model.add(Dense(unit, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [47]:
from tensorflow.keras.layers import Input

# Change project_name to start a fresh tuning session and avoid the shape mismatch error
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    project_name='diabetes_optimization_v2')

In [48]:
# Re-running the search to ensure trials are completed before retrieving results
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7467532753944397

Best val_accuracy So Far: 0.7467532753944397
Total elapsed time: 00h 00m 14s

In [49]:
# Retrieve models only if the search has completed
best_models = tuner.get_best_models(num_models=1)
if best_models:
    model = best_models[0]
    model.summary()
else:
    print('No models found. Please ensure tuner.search() has finished running trials.')

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 161 (644.00 B)

 Trainable params: 161 (644.00 B)

 Non-trainable params: 0 (0.00 B)

# How to select number of layers for hypertuning

In [53]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def build_model(hp):
    model = keras.Sequential()
    model.add(layers.Input(shape=(X_train.shape[1],)))
    for i in range(hp.Int("num_layers", 1, 3)):
        model.add(
            layers.Dense(
                units=hp.Int(f"units_{i}", min_value=32, max_value=512, step=32),
                activation=hp.Choice("activation", ["relu", "tanh"]),
            )
        )
    if hp.Boolean("dropout"):
        model.add(layers.Dropout(rate=0.25))

    # Fixed for binary classification (Diabetes dataset)
    model.add(layers.Dense(1, activation="sigmoid"))

    learning_rate = hp.Float("lr", min_value=1e-4, max_value=1e-2, sampling="log")
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        loss="binary_crossentropy",
        metrics=["accuracy"],
    )
    return model

tuner = kt.RandomSearch(
    hypermodel=build_model,
    objective="val_accuracy",
    max_trials=3,
    executions_per_trial=2,
    overwrite=True,
    directory="my_dir",
    project_name="helloworld",
)

In [58]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))
model=tuner.get_best_models(num_models=1)[0]
model.summary()

Trial 4 Complete [00h 00m 09s]
val_loss: 0.5216629505157471

Best val_loss So Far: 0.5038136839866638
Total elapsed time: 00h 00m 29s

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [66]:
model.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.7573 - loss: 0.4932 - val_accuracy: 0.7922 - val_loss: 0.4971
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7606 - loss: 0.4825 - val_accuracy: 0.7857 - val_loss: 0.4954
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7622 - loss: 0.4765 - val_accuracy: 0.7857 - val_loss: 0.4940
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7671 - loss: 0.4711 - val_accuracy: 0.7987 - val_loss: 0.4927
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7720 - loss: 0.4664 - val_accuracy: 0.7987 - val_loss: 0.4920
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4624 - val_accuracy: 0.7987 - val_loss: 0.4915
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7752 - loss: 0.4589 - val_accuracy: 0.7857 - val_loss: 0.4910
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4556 - val_accuracy: 0.7792 - val_loss: 0.4911
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4526 - val_accuracy: 0.7792 - val_loss: 0.4921
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4507 - val_accuracy: 0.7792 - val_loss: 0.4943
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4480 - val_accuracy: 0.7792 - val_loss: 0.4955
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4464 - val_accuracy: 0.7857 - val_loss: 0.4967
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4445 - val_accuracy: 0.7792 - val_loss: 0.4980
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4432 - val_accuracy: 0.7792 - val_loss: 0.4989
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4417 - val_accuracy: 0.7727 - val_loss: 0.5009
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4406 - val_accuracy: 0.7792 - val_loss: 0.5017
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4390 - val_accuracy: 0.7792 - val_loss: 0.5026
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4384 - val_accuracy: 0.7792 - val_loss: 0.5031
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4375 - val_accuracy: 0.7727 - val_loss: 0.5050
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4363 - val_accuracy: 0.7792 - val_loss: 0.5062
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4354 - val_accuracy: 0.7792 - val_loss: 0.5062
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4345 - val_accuracy: 0.7662 - val_loss: 0.5072
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4338 - val_accuracy: 0.7662 - val_loss: 0.5083
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4329 - val_accuracy: 0.7662 - val_loss: 0.5100
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4322 - val_accuracy: 0.7662 - val_loss: 0.5096
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4312 - val_accuracy: 0.7792 - val_loss: 0.5108
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4307 - val_accuracy: 0.7727 - val_loss: 0.5105
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4300 - val_accuracy: 0.7727 - val_loss: 0.5116
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4289 - val_accuracy: 0.7727 - val_loss: 0.5124
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4284 - val_accuracy: 0.7727 - val_loss: 0.5134
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4276 - val_accuracy: 0.7727 - val_loss: 0.5136
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4269 - val_accuracy: 0.7727 - val_loss: 0.5152
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4263 - val_accuracy: 0.7662 - val_loss: 0.5146
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4252 - val_accuracy: 0.7727 - val_loss: 0.5175
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4248 - val_accuracy: 0.7727 - val_loss: 0.5173
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4246 - val_accuracy: 0.7727 - val_loss: 0.5198
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4241 - val_accuracy: 0.7597 - val_loss: 0.5188
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4231 - val_accuracy: 0.7662 - val_loss: 0.5184
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4230 - val_accuracy: 0.7662 - val_loss: 0.5188
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4224 - val_accuracy: 0.7662 - val_loss: 0.5186
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4219 - val_accuracy: 0.7662 - val_loss: 0.5202
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4211 - val_accuracy: 0.7662 - val_loss: 0.5208
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4206 - val_accuracy: 0.7662 - val_loss: 0.5226
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4204 - val_accuracy: 0.7662 - val_loss: 0.5228
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4198 - val_accuracy: 0.7662 - val_loss: 0.5230
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4193 - val_accuracy: 0.7662 - val_loss: 0.5235
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4186 - val_accuracy: 0.7662 - val_loss: 0.5232
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4180 - val_accuracy: 0.7662 - val_loss: 0.5226
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4179 - val_accuracy: 0.7662 - val_loss: 0.5243
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4169 - val_accuracy: 0.7662 - val_loss: 0.5224
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4168 - val_accuracy: 0.7662 - val_loss: 0.5226
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4163 - val_accuracy: 0.7662 - val_loss: 0.5245
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4158 - val_accuracy: 0.7662 - val_loss: 0.5250
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4153 - val_accuracy: 0.7662 - val_loss: 0.5253
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4152 - val_accuracy: 0.7662 - val_loss: 0.5251
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4148 - val_accuracy: 0.7597 - val_loss: 0.5264
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4147 - val_accuracy: 0.7597 - val_loss: 0.5275
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4140 - val_accuracy: 0.7597 - val_loss: 0.5269
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4134 - val_accuracy: 0.7662 - val_loss: 0.5262
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4130 - val_accuracy: 0.7662 - val_loss: 0.5273
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4130 - val_accuracy: 0.7662 - val_loss: 0.5280
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4124 - val_accuracy: 0.7662 - val_loss: 0.5282
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4119 - val_accuracy: 0.7662 - val_loss: 0.5290
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4120 - val_accuracy: 0.7597 - val_loss: 0.5304
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4114 - val_accuracy: 0.7597 - val_loss: 0.5302
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4109 - val_accuracy: 0.7597 - val_loss: 0.5307
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4106 - val_accuracy: 0.7597 - val_loss: 0.5302
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4103 - val_accuracy: 0.7597 - val_loss: 0.5302
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4098 - val_accuracy: 0.7597 - val_loss: 0.5302
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4098 - val_accuracy: 0.7662 - val_loss: 0.5297
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4093 - val_accuracy: 0.7662 - val_loss: 0.5294
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4094 - val_accuracy: 0.7597 - val_loss: 0.5313
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4088 - val_accuracy: 0.7597 - val_loss: 0.5303
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4083 - val_accuracy: 0.7662 - val_loss: 0.5298
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4080 - val_accuracy: 0.7597 - val_loss: 0.5309
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4077 - val_accuracy: 0.7597 - val_loss: 0.5309
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8046 - loss: 0.4075 - val_accuracy: 0.7597 - val_loss: 0.5315
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8078 - loss: 0.4068 - val_accuracy: 0.7597 - val_loss: 0.5323
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.8046 - loss: 0.4066 - val_accuracy: 0.7532 - val_loss: 0.5334
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8062 - loss: 0.4067 - val_accuracy: 0.7468 - val_loss: 0.5341
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8046 - loss: 0.4058 - val_accuracy: 0.7532 - val_loss: 0.5352
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4060 - val_accuracy: 0.7532 - val_loss: 0.5339
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4055 - val_accuracy: 0.7468 - val_loss: 0.5348
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8046 - loss: 0.4056 - val_accuracy: 0.7468 - val_loss: 0.5348
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8046 - loss: 0.4051 - val_accuracy: 0.7468 - val_loss: 0.5345
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8029 - loss: 0.4051 - val_accuracy: 0.7532 - val_loss: 0.5347
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8013 - loss: 0.4044 - val_accuracy: 0.7597 - val_loss: 0.5350
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8046 - loss: 0.4042 - val_accuracy: 0.7597 - val_loss: 0.5362
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4041 - val_accuracy: 0.7597 - val_loss: 0.5354
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4036 - val_accuracy: 0.7468 - val_loss: 0.5351
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4033 - val_accuracy: 0.7597 - val_loss: 0.5367
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4030 - val_accuracy: 0.7468 - val_loss: 0.5376
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4028 - val_accuracy: 0.7468 - val_loss: 0.5361
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4024 - val_accuracy: 0.7468 - val_loss: 0.5367
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4023 - val_accuracy: 0.7532 - val_loss: 0.5368
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4021 - val_accuracy: 0.7468 - val_loss: 0.5358
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4020 - val_accuracy: 0.7532 - val_loss: 0.5353
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4016 - val_accuracy: 0.7468 - val_loss: 0.5359
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4014 - val_accuracy: 0.7468 - val_loss: 0.5382
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4009 - val_accuracy: 0.7468 - val_loss: 0.5384

In [65]:
model

AttributeError: 'HyperParameters' object has no attribute 'value'